# Generated by Django 5.2.5 on 2025-10-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
